---
title: "Er reproduserbarhet nok?"
author: "Kenny Eines Kristiansen"
date: last-modified
date-format: "dddd D MMM, YYYY"
csl: apa7.csl
# nynorsk
#lang: no-NN
lang: no-NB
# for typst with bibtex
citeproc: true
papersize: a4
format:
  html: default
  typst: default
# krever at tinytex er installert
#  pdf:
#    papersize: a4
bibliography: reproducibility.bib
abstract: "Et kort sammendrag, en til to avsnitt."
---

## Introduksjon

Reproduserbarhet er et viktig prinsipp innen for vitenskaplig forskning, ettersom dette vil gjøre det mulig for andre forskere å bruke de samme dataene og analysemetodene for å undersøke om de oppnår det samme resultatet[@goodman2016b]. At forskningsresultatet kan reproduseres, betyr imidlertid ikke at resultatet nødvendigvis vil kunne bli gjenskapt med nye data eller andre forhold. Dette reiser spørsmål om hvorvidt reproduserbarhet alene er tilstrekkelig for å sikre pålitelige forskningsresultater. Andre faktorer som replikerbarhet, generaliserbarhet og validitet, kan også være sentrale når forskningsresultater skal vurderes.

I denne artikkelen vil derfor diskutere om reproduserbarhet er tilstrekkelig, eller om det bør stilles ytterligere krav til vitenskapelig forskning. Videre blir det også diskutert hvordan Quarto kan bidra til reproduserbare forskningsprosesser, i tillegg til hvilke utfordringer som fortsatt gjenstår.

## Litteraturgjennomgang

For å vurdere om reproduserbarhet er tilstrekkelig alene, er det viktig å skille mellom reproduserbarhet, replikerbarhet og generaliserbarhet. Reproduserbarhet innebærer at et tidligere resultat skal kunne gjenskapes ved bruk av de samme dataene og analysemetodene[@goodman2016b]. Replikerbarhet innebærer at resultatet undersøkes ved hjelp av nye data, mens generaliserbarhet handler derimot på sin side om hvorvidt resultatene også gjelder i andre kontekster eller populasjoner[@bollen2015].

Reproduserbarhet er videre ikke nødvendig nok bare på grunnlag om at resultatet kan gjenskapes på bakgrunn med de samme dataene og metodene[@munafò2017]. Det sier derimot ingenting om resultatet holder når studien gjennomføres med enten nye data eller andre forhold[@klein2018b]. I tillegg er det viktig å vurdere om resultatene kan generaliseres til andre kontekster eller populasjoner, samt om studien faktisk måler det den har til hensikt å undersøke. Altså studiens validitet.

Betydningen av replikerbarhet har blitt særlig tydelig gjennom det som omtales som replikasjonskrisen. Flere forskningsresultater som tidligere ble sett på som gode og etablerte studier har vist seg å være vanskelige å gjenskape senere med nye data[@opensciencecollaboration2015]. På grunn av dette har det blitt skapt spørsmål om hvor robuste de enkelte publiserte forskningsresultatene faktisk er.

Open Science Collaboration forsøkte å replikere 100 publiserte psykologistudier. Her viste det seg at en betydelig lavere andel av replikasjonene ga statistisk signifikante resultater enn de opprinnelige studiene[@opensciencecollaboration2015]. Dette viser hvorfor et forskningsresultat ikke nødvendigvis kan bli sett på som robust bare fordi det først har gitt et signifikant resultat.

En mulig årsak til utfordringer med replikerbarhet er publiseringsskjevhet. Dersom studier med statistisk signifikante resultater har en større sannsynlighet for å bli publisert enn studier som ikke kommer med signifikante funn, kan forskningslitteraturen som er tilgjengelig bidra til et skjevt bilde av den faktiske effekten[@iyengar1988b].

For å redusere slike problemer kan økt åpenhet rundt forskningsprosessen være et viktig tiltak for å styrke reproduserbarheten. Hvis forskere gjør både data, analysemetoder og kode tilgjengelig, vil det være enklere for andre å kontrollere hvordan resultatene er produsert, samt enklere å forsøke å gjenskape analysene[@nosek2015].

Det å gjøre forskningsmaterialet tilgjengelig er imedlertid ikke nødvendigvis tilstrekkelig nok dersom det er vanskelig å forstå hvordan analysen er gjennomført. En reproduserbar forskningsprosess bør derfor gjøre det mulig å følge stegene fra data og analyse helt til det ferdige resultatet[@allaire2020b]. Her kommer digitale verktøy som kombinerer tekst, kode og resultater til god nytte. Et eksempel er Quarto, som gjør det mulig å samle tekst, kode og analyseresultater i samme dokument[@lefoll2026].

Versjonskontroll er også noe som kan være viktig i en reproduserbar forskningsprosess. Ved å lagre endringer underveis muliggjør det å følge utviklingen i analysen, og se hvilke endringer som er gjort i data, kode og dokumentasjon[@ram2013].

## Diskusjon av forskningsspørsmålet (problemstillingen)

- Burde replikerbarhet være et krav eller er det å be om for mye?
- Kan Quarto dokumenter hjelpe med å oppnå reproduserbarhet?
- Hvilke problem gjenstår og hvordan kan disse løses?

## Konklusjon

Noen kloke ord.

## Referanser

::: {#refs}
:::

## Appendiks A

- Versjon nummer og referanse til R pakken brukt i dokumentet
- R versjon brukt, med referanse

## Appendiks B

- Hvordan er KI brukt
- Husk invitasjon til chat
